import type { Metadata, Viewport } from "next";
import { Toaster } from "sonner";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";

const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#F7F7F8",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${robotoSerif.variable} min-h-dvh w-full overflow-x-hidden antialiased`}
    >
      <body className="min-h-dvh w-full overflow-x-hidden bg-[#F7F7F8] text-zinc-900">
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
